### ISSUE TITLE
`facilitator`: consume task queue messages on un-retryable failure

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#1001]
While we have retry loops with exponential backoffs around cloud API transactions, we also rely on GCP PubSub and AWS SQS message redelivery to provide retries in the face of transient failures such as lapses in availability of cloud storage. However, we don't currently distinguish between retryable failures (e.g., HTTP 500 from Google Cloud Storage) and unretryable failure (e.g., a batch file whose signature is invalid). As a consequence, we will fruitlessly retry tasks that can never possibly succeed up to five times, which wastes compute resources.

We should try to annotate errors in `facilitator` into retryable and and non-retryable categories. In the face of the latter, `facilitator` should acknowledge/consume the PubSub/SQS message, and if possible, send it directly to a dead letter queue for analysis by operators.

**Comment by tgeoghegan** [comment]
#416 contains a long since outdated attempt at starting on this.

**Comment by BranLwyd** [comment]
I like this idea; I think it's important that a non-retryable error still end up in the DLQ to allow for later analysis, and probably because it will make alerting easier.
