### ISSUE TITLE
Discover parameters from peer manifests in workflow manager

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#104]
For Narnia and the foreseeable future, the workflow manager won't know how to discover peer manifests or validate batch signatures, instead delegating that work to individual facilitator (data plane) jobs. That will make it harder to restrict network egress for those jobs. We can move this work into the workflow manager and have it hand static parameters to facilitator jobs it runs.

**Comment by yuriks** [comment]
Going one step further: It would be great if the workflow manager *also* received static configuration (generated by a job that reads the manifests on a regular basis), isolating the "run every 10 minutes" job from having to make http requests to a bunch of different urls and validating configuration on its own.
