### ISSUE TITLE
Monitoring dashboards

### ISSUE THREAD

**Issue by branlwyd** [divviup/prio-server#1106]
The prio-server infrastructure generates metrics, which are collected by a Prometheus deployment that is deployed by default. But none of the relevant systems (Prometheus/Grafana/CloudWatch/Cloud Monitoring) have dashboards set up by default showing relevant metrics. Currently, a custom query has to be built to see a graph.

We should build a default set of metrics that provide useful "at-a-glance" information about a prio-server deployment. This may have helped detect the issue leading to the 2021-10-26 postmortem.

**Comment by tgeoghegan** [comment]
#234 feels related. The only remaining action there would be to provide a means of reaching Grafana or Prometheus without `kubectl port-forward`, but we could also decide that what we've got is good enough.
