### ISSUE TITLE
Migrate from autoscaling/v1 to autoscaling/v2

### ISSUE THREAD

**Issue by divergentdave** [divviup/prio-server#1629]
#1622 introduced support in Terraform for the `kubernetes_horizontal_pod_autoscaler_v2` resource. We currently manage unversioned `kubernetes_horizontal_pod_autoscaler` resources. HPA on autoscaling/v2 are available as of Kubernetes 1.23, which we are not using yet in our clusters.

The unversioned `kubernetes_horizontal_pod_autoscaler` autodetects whether to use v1 or v2beta2 APIs, based on attributes set on resources, and we currently use the v1 API. The unversioned resources will be [deprecated and removed in the next two provider major versions](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources); we should keep an eye on this, and migrate if needed.

**Comment by tgeoghegan** [comment]
The long pole for moving to `_v2` will be availability of Kubernetes 1.23 in EKS and GKE. Is there any reason not to move the TF autoscaler resources to the `_v1` versions now? Normally I'd worry about migrating resources in tfstate, but I think destroying and replacing pod autoscalers should be harmless.

**Comment by divergentdave** [comment]
Sure, that sounds good. I think the only impact would be a bump in the control loop.
