### ISSUE TITLE
Post to Slack on release of `prio-server`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#1632]
@hostirosti requested that we hook something up so that one or two channels in the ENPA slack get automated notifications when we cut a new release of the `prio-server` container images.

**Comment by tgeoghegan** [comment]
@divergentdave It looks like you've already figured out how to get this working.

**Comment by hostirosti** [comment]
Yep run `/github subscribe divviup/prio-server releases` in the [#global-operations](https://enpa-collab.slack.com/archives/C033K3WNC2V) and [#prod-operations](https://enpa-collab.slack.com/archives/C01H7G24N1K) channels. Thank you!

**Comment by divergentdave** [comment]
Done!
