### ISSUE TITLE
Profile memory usage of workflow-manager

### ISSUE THREAD

**Issue by divergentdave** [divviup/prio-server#1757]
A recent worst-case execution of workflow-manager in a large locality consumed about 5GB of memory at peak, likely driven by newly-arrived ingestion batches. We should take a memory profile and look for any easy wins to reduce the working set size.

**Comment by tgeoghegan** [comment]
I've done work in this direction in the past: the reason that `workflow-manager` discovers the aggregations in the bucket and handles them one at a time is to reduce the instantaneous memory footprint. I think the way forward here would be to chunk up the discovery work temporally, e.g., consider one hour's worth of objects at a time.

**Comment by divergentdave** [comment]
Using `runtime/pprof` is the best way to get a heap profile, as the runtime is already doing sampled stack collection for it by default. As a first effort, we can collect a heap profile once, just before program exit. This won't tell us what objects were live at the point of peak memory consumption, but it will tell us if there are any leaks (i.e. due to reference cycles) and provide the distribution of all allocated memory across the program.

The simplest way to retrieve profiles for analysis would be to either create a new CronJob with the `--dry-run` argument passed or modify the existing CronJob, add an emptyDir volume mount to the container, add a flag to enable writing memory profiles into that volume, and grab several profiles for analysis with `kubectl cp`. (around peak time, and in the biggest locality's namespace) We should have about 50 minutes to grab each profile before the pod and its volume are deleted, assuming the underlying node sticks around.

**Comment by divergentdave** [comment]
This plan did not work out:

```
$ kubectl cp ...
error: cannot exec into a container in a completed pod; current phase is Succeeded
```

The most natural solution would be to mount some kind of PersistentVolume with an accessMode of ReadWriteMany, and store profiles there.

**Comment by divergentdave** [comment]
I realized we already collect `go_memstats_` metrics prior to program exit, so we have some summary historical data already. Unfortunately, the most extreme examples have rolled off our TSDB retention period. Since then, the ingestion batches we receive have been more spread out through the day. Here are some charts of top-line numbers to contextualize memory usage over the past month.

`go_memstats_sys_bytes`, this shows us how much virtual memory the runtime acquired, which gives us an approximation of the peak memory consumption. Here, we only see up to 3GB, not 5GB. These numbers are roughly in line with `container_memory_max_usage_bytes`, though the sampling is much more reliable.
![image](https://user-images.githubusercontent.com/181772/180306818-f6894b0c-60b0-47b2-b07c-2ff4437e09ca.png)

`go_memstats_alloc_bytes_total`, this shows us the cumulative amount of memory allocated on the heap. We see that it is several times the virtual memory acquired, so heap space was reused many times.
![image](https://user-images.githubusercontent.com/181772/180306726-4d0f0281-5c8c-4c87-a147-a2c26ad0f20f.png)

`go_memstats_mallocs_total`, this shows us the cumulative number of allocations made throughout the program. This varies within a surprisingly tight band, compared to the byte measurements.
![image](https://user-images.githubusercontent.com/181772/180306639-796f3827-54ac-4ba6-9658-420b46a73829.png)

At this point, we could take some production memory profiles at our leisure for analysis, but smoother ingestor behavior has removed the urgency. Under development/staging workloads, there is very little to measure, but the largest allocations showed up as coming from the HTTP request stack used by the GCS client.
