### ISSUE TITLE
Have portal server specify aggregation window and grace period to data share processors

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#183]
It's also crucial that ISRG and NCI be using the same parameters for the aggregation window and grace period. Otherwise, you'll have (for instance) NCI doing sum parts over six hour windows and ISRG over five, and the data will be difficult to reconcile, at best.

@jsha's bright idea for this is to have the portal server control this value by advertising aggregation window and grace period values from its global manifest, which data share processors would then use to configure their workflow-manager jobs.

**Comment by krazykid** [comment]
We can update the portal's `global_manifest.json` file. I would recommend that you put in defaults though if the values are not in the `global_manifest.json`. Feel free to send me where in the JSON file things should go.
