### ISSUE TITLE
Don't create `invalid_uuid_#.avro` file unless there are rejected packets.

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#217]
I was intently watching logs from an aggregation job during the Narnia test and saw this statement go by:

```
[2020-11-18T23:23:31Z INFO  facilitator::transport::gcs] put gs://isrg-sum-bucket-43acc70e-1d18-6c5a-73ae-825dc897b8b1//ta-ta-apple/com.apple.EN.UserRisk.e092abc519845e88e361edba2445ac2f353e067c9d95b76d5f3d11a1364e5197/202011182200-202011182230.invalid_uuid_1.avro as OauthTokenProvider { account_to_impersonate: Some("prio-gamlin-test-sum-writer@gamlin-test.iam.gserviceaccount.com"), default_service_account_key_file: None, default_account_token: None, impersonated_account_token: None }
```

At first I thought this indicated that at least one packet had been rejected due to an invalid proof, but that's not the case. Rather, it's because we unconditionally make the API call to initiate a streaming upload, before we know if any invalid packets will be generated. We should check if orphaning these uploads is a problem, and if so, either reap them or avoid creating them unnecessarily.

[facilitator-aggregate.log](https://github.com/abetterinternet/prio-server/files/5563410/facilitator-aggregate.log)

**Comment by bmw** [comment]
I looked into this a bit and had a couple of questions.

1. How do we "check if orphaning these uploads is a problem"? My understanding is this depends on the behavior of the portal server. Do we know if creating these empty files is a problem or if no longer creating them at all will create new ones? If we don't know, is this something I can help?
2. The [sum-part](https://github.com/abetterinternet/prio-server/blob/main/avro-schema/sum-part.avsc) message created along with the `invalid_uuid_#.avro` file contains a `packet_file_digest` field which is the SHA256 hash of the `invalid_uuid_#.avro` file. Currently in the case of no rejected packets, `packet_file_digest` contains the SHA256 hash of the empty string. If we're no longer creating this file, what should the value of this field be?

**Comment by tgeoghegan** [comment]
1. My concern here is motivated by the roughly equivalent Amazon API, whose [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) states:
>After you initiate a multipart upload and upload one or more parts, you must either complete or stop the multipart upload in order to stop getting charged for storage of the uploaded parts. Only after you either complete or stop a multipart upload will Amazon S3 free up the parts storage and stop charging you for the parts storage. 

On the GCS side, we're using [resumable uploads](https://cloud.google.com/storage/docs/performing-resumable-uploads). In the case I describe in this issue, we do the initial POST to create the resumable upload, but none of the subsequent PUTs to provide content or complete the upload, because there is no content to upload. I think we probably should be explicitly [canceling the resumable upload](https://cloud.google.com/storage/docs/performing-resumable-uploads#cancel-upload) when that happens, and I'm not sure whether or not it's a problem that we don't.

2. Ooh, good catch. We should have accounted for the fact that the invalid UUID file is optional, and accordingly made the `packet_file_digest` field optional in the Avro message specification. The bad news is that changing those schemas is a pain because it requires coordination across multiple servers (in this case, us, NCI and MITRE). I think continuing to insert the hash of the empty string is fine.
