### ISSUE TITLE
Set up Grafana

### ISSUE THREAD

**Issue by jsha** [divviup/prio-server#234]
Right now we just have Prometheus for metrics gathering. We'd like to also have Grafana in front of it. We'll also need to configure Grafana to be able to authenticate team members.

**Comment by tgeoghegan** [comment]
This is mostly resolved by #285, except that we cheekily use `kubectl port-forward` to access Grafana. I'll keep this open to track the tasks of exposing Grafana on an external IP and configuring authenticated access to it.

**Comment by tgeoghegan** [comment]
I agree with you. It'd be nice to remove the barrier of needing `kubectl` and valid Kubernetes credentials, but what we've got here is good enough for the foreseeable future. There's plenty of observability and perf tasks I'd take on before investing a lot of time in this.
