### ISSUE TITLE
Figure out how to embed git SHA into Terraform state

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#274]
It would be nice if we could query a deployed env to find out what git SHA it was `terraform apply`ed from.

**Comment by aaomidi** [comment]
Hmm, think we can do a local command exec for git and then put that into a ConfigMap in the default namespace?

**Comment by tgeoghegan** [comment]
I was hoping there would be some way to bake it into the .tfstate but a config map is not a bad approach at all.
