### ISSUE TITLE
Can't SSH into worker VMs

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#288]
I wanted to SSH into a worker VM to check some `ulimits` but found that the `gcloud ssh` stuff doesn't work. My guess is that our private network configuration might not allow ingress to nodes on port 22. Anyway we should figure out how to SSH into workers.

**Comment by pgporada** [comment]
Here's a doc that may help https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-ssh#test_connectivity

**Comment by tgeoghegan** [comment]
#1221 addresses this for GKE, but I don't yet know how to do it for EKS. There is the EC2 keypair feature, but it's not clear to me how to make that work usefully for multiple operators.
