### ISSUE TITLE
Make writing out validation batches atomic/idempotent

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#362]
As it turns out, #343 was the wrong solution. The problem is that if PHA and facilitator emit sum parts for an aggregation window and they don't contain the exact same set of packets, they cannot be meaningfully summed: if one side's sum contains shares that aren't matched on the other side, then the resulting sums would be off by an unknowable amount.

Our analysis of these failures so far shows that the problem is split generations of validation batches. We suspect that because GCP PubSub subscriptions and AWS SQS queues both have at-least-once delivery semantics, we sometimes see an intake job run successfully twice, with the two runs racing to emit own and peer validation batches. You can then end up with a validation batch where the packet file and the header are from one task, but the signature is from another, and thus the signature no longer matches (because Avro encoding is non-deterministic). Or, you could have the signature and header from one run, but the packet file is from another, and the digest in the header won't match the measured digest of the packet file.

The first thing I need to do is convince myself that the problem is split generations as I suspect, which I can do by analyzing logs and peer validations.

Once I have convinced myself of the problem, what I'm going to do is make the writing of validations atomic, in order to make intake batch tasks idempotent (or at least more idempotent). Then, we will have to carefully consider how to migrate from the old (three file) batch format to the new (single file) format.

- [ ] Teach `facilitator` to emit own and peer validation batches as single objects, probably as `tar` archives of the existing three files
- [ ] Make sure `facilitator` can read in validations in either format
- [ ] Add a flag to `facilitator` that makes it emit batches in the new format; the default behavior is the old format
- [ ] have facilitator emit metrics to count validation batches in old format vs. new format

Once we have those changes, we can coordinate deploys thusly:

- Release `facilitator` image
- ISRG and NCI both deploy new facilitator to production
- Once NCI has been assured ISRG is on the new version, NCI flips the configuration flag to emit validations in new format
- Once ISRG has been assured NCI is on the new version, ISRG flips the configuration flag to emit validations in new format
- Once certain that no old-format validations are being read (i.e. by determining the metric for old format batches has been 0 for some time), ISRG and NCI can deploy a `facilitator` that no longer honors old-format batches (#363).

**Comment by tgeoghegan** [comment]
At the moment, we're only talking about doing this for validation batches, so that we don't have to force either ingestion servers or the portal server to update their implementation of serialization or deserialization of batches. We might want ingestion batches and sum parts to eventually adopt this.

**Comment by tgeoghegan** [comment]
#391 wound up addressing the root cause of the problem we were having with a lot less work. That said, this change is still a good idea: it would make us resilient to other split generation problems, and also would be a performance win, because it would cut the number of cloud storage round trips significantly (especially if we did it for all batch types). So while this isn't urgent anymore, I want to keep the issue around.

**Comment by BranLwyd** [comment]
[tagging this for `ops-due-diligence` to allow discussion; I think the *goal* of this bug is obviously desirable, but I'm not fully sure as to the level of effort required.]

**Comment by BranLwyd** [comment]
The immediate dev work is done. What's left for this bug:
1) wait for all parties (ISRG & NIH for the prod-us deployment, ISRG & Google for the intl deployment) to release past https://github.com/abetterinternet/prio-server/commit/b398b86f7c2518d7ffef4adb5b61647638901c68.
2) deploy a config change to enable `--write-single-object-validation-batches` in all environments.
