### ISSUE TITLE
facilitator: Stop honoring old format validation batches

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#363]
Once we have completed the transition described in #362, we can make `facilitator` only accept validation batches in the new, single-object format, and raise errors if we see the old style.

**Comment by tgeoghegan** [comment]
When we do this, we should also re-enable the integrity checks disabled by #542 / #548.

**Comment by BranLwyd** [comment]
The integrity checks have fired at least four times in the prod-us deployment in the last month, so I think this is worthy to address.

**Comment by tgeoghegan** [comment]
Keep in mind that we have to coordinate the deployment of this change with our distinguished colleagues at NCI and Google.
