### ISSUE TITLE
Decide what goes into `encryption_key_id` field on `PrioDataSharePacket`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#74]
Eventually, both Apple and Google servers will be populating the `encryption_key_id` field in the `PrioDataSharePacket` messages they send. For data share processors to handle them generically, we need to agree on what value goes in there, and make sure it's a value that lets the data share processor look up the appropriate packet decryption key. We would have to make sure that whatever value we use is available to both Apple and Google ingestion servers and mobile devices, as necessary.

One proposal is the serial number of the X.509 certificate used to transmit the packet encryption key to Apple.

**Comment by yuriks** [comment]
I'd vote for just a hash of the key
